FrameItems:
  enable: true
  title: "&6&lFrameItems &8>>"
  size: 9

ArenaClear:
  arena1:
    world: "world"
    from:
      x: 0
      y: 0
      z: 0
    to:
      x: 50
      y: 50
      z: 50
    ExceptBlocks:
      - "BEDROCK"
      - "BARRIER"
      - "COMMAND_BLOCK"
  nether:
    world: "world_nether"
    from:
      x: 0
      y: 0
      z: 0
    to:
      x: 50
      y: 50
      z: 50
    ExceptBlocks:
      - "BEDROCK"
      - "BARRIER"
      - "COMMAND_BLOCK"
RespawnRegular:
  clearinventory: true
  enable: true
  world: 'world_nether'
  x: 0
  y: 50
  z: 0
